### PR TITLE
Update to angular 10

### PR DESCRIPTION
**Pull request by frankadrian**

### CODE REVIEW

**Comment by kroeder** [comment]
Is something blocking this PR? It is currently blocking the update to 10.1 in apps because of the missing generic for `ModuleWithProviders<...>`

I did a quick review and the PR is looking good! Angular 10.1.2 is now available, though. 🙂

**Comment by frankadrian** [comment]
Nothing blocking this as far as I know. Just needs to be merged.
The peer dependencies specify "@angular/core": ">=10.0.0" so I don't think this should be a problem with 10.1 :)

**Comment by SirZach** [comment]
Can we merge this PR? I'm running into the same issue that @kroeder is running into, trying to update an app to v10. Thanks!

**Comment by ihym** [comment]
I'll look into it this weekend. Thanks!

**Comment by SirZach** [comment]
@ihym any chance to get a look at it over the last few days?

**Comment by ihym** [comment]
ngx-timeago@2.0.0

**Pull request closed without merging**
